### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by GK67**
I think I only changed MyDrawer files and Configuration files

### CODE REVIEW

**Review by royJackman — CHANGES_REQUESTED** [review]
Please don't hardcode padding values, use some proportion of the whole screen. Besides that, all good

**Review by neal-merkl — CHANGES_REQUESTED** [review]
the configuration folder should be inside the `HPEMobileApp/app` folder. Move the folder and update all file names. Same thing applies to the `my-drawer` folder.  There's also no need to keep the `shared` folder

Also it doesn't look like the configuration page is reachable from anywhere?

Also you have code for the menu app drawer inside here, but it looks like that already exists in master. Please verify.

**Comment by GK67** [comment]
will update it later on, have trouble with school wifi right now.thx

2017年11月26日星期日，Alfonso Merkl <notifications@github.com> 写道：

**Comment by GK67** [comment]
Hi,

First of all , I have changed absolute_layout to grid_layout in my XML
file, since you do not want to hardcore those padding values, but it may
looks a little bit ugly compare to absolute layout.

Secondly ,the configuration and update_system folder is belong to app
folder, which means they are at same level of featured, home,search folders.

in my version of application, the configuration page can be reached by
my_draw. and update_system page is a function belong to configuration page,
can be trigger by a button. I will mail you free screen shots that will
explain.[image: 内嵌图片 1][image: 内嵌图片 2][image: 内嵌图片 3]
and also I will update whole application to github instead just few files.
if there are any changes, tell me

Thanks
Shipeng Yu

2017-11-26 21:21 GMT-05:00 shipeng yu <shipeng123@gmail.com>:

**Comment by GK67** [comment]
I am confused how github really works for upload files. it always wont let
me put my file in a right directory. [image: 内嵌图片 1] configuration and
updatesystem  supposed belong to App folder , but github pull that out

2017-11-27 15:16 GMT-05:00 shipeng yu <shipeng123@gmail.com>:

**Pull request closed without merging**
