### PR TITLE
Graph

### PR DESCRIPTION
**Pull request by zsaziz**
Code for graph pages

### CODE REVIEW

**Review by neal-merkl — CHANGES_REQUESTED** [review]
These pages don't look like they're reachable from anywhere?

**Comment by zsaziz** [comment]
The graphs are accessible from the home page when you tap on one of the graph icons.

**Comment by zsaziz** [comment]
If you’re talking about the graph-view-model.js page then I didn’t make any changes to that. I just copied it from the default layout for another page.

**Comment by zsaziz** [comment]
I updated the graph names and the button names so they are more specific to the type of graphs.

**Review by neal-merkl — APPROVED** [review]
lgtm

**Pull request merged**
